#!/usr/bin/env bash
# Model-check the CAS-carries-the-announce LightEpoch fix and report each result
# against its expectation. Requires Java + tla2tools.jar (see Dockerfile), or set
# TLA_TOOLS to the path of tla2tools.jar.
#
# Pass a substring to run only the matching rows, e.g.
#   ./run.sh CasAnnounceResumeRefreshWeak_acqload_armlb
# Set LE_KEEP_CFG=1 to leave the generated .cfg files on disk afterwards, which
# is what you want if you intend to open one in the TLA+ Toolbox.
set -u

JAR="${TLA_TOOLS:-/opt/tla2tools.jar}"
HERE="$(cd "$(dirname "$0")" && pwd)"
FIXES="$HERE/epoch/fixes"
# -DTLA-Library lets specs in epoch/fixes/ resolve the shared MODULE StoreBuffer
# and MODULE WeakMemory, which live at the top of this folder.
TLC=(java -XX:+UseParallelGC "-DTLA-Library=$HERE" -cp "$JAR" tlc2.TLC -workers auto -deadlock -cleanup)
failures=0
matched=0
FILTER="${1:-}"

# Which invariants to check is a property of the spec -- each one defines its own
# -- so it belongs here rather than repeated across a .cfg per memory model. TLC
# takes exactly one -config per run, so the table below plus each row's constants
# are expanded into a throwaway .cfg at run time.
declare -A INVARIANTS=(
  [CasAnnounceOneReader]="NoUseAfterFree AnnounceVisibleWhileProtected"
  [CasAnnounceTwoReaders]="NoUseAfterFree SlotExclusive ThreadIdIntact"
  [CasAnnounceTwoReadersNoCas]="NoUseAfterFree SlotExclusive ThreadIdIntact"
  [CasAnnounceTwoReadersPlainRelease]="NoUseAfterFree SlotExclusive ThreadIdIntact"
  [CasAnnounceTwoReadersNoThreadId]="NoUseAfterFree SlotExclusive"
  [CasAnnounceTwoReadersNoThreadIdNoCas]="NoUseAfterFree SlotExclusive"
  [CasAnnounceSymmetricPeers]="NoUseAfterFree SlotsDisjoint AnnounceVisibleWhileProtected"
  [CasAnnounceSymmetricPeersNoCas]="NoUseAfterFree AnnounceVisibleWhileProtected"
  [CasAnnounceNoThreadId]="NoUseAfterFree SlotExclusive OwnedSlotNotWiped AnnounceVisibleWhileProtected"
  [CasAnnounceNoThreadIdNoCas]="NoUseAfterFree SlotExclusive OwnedSlotNotWiped AnnounceVisibleWhileProtected"
  [CasAnnounceNoThreadIdStaleIndex]="NoUseAfterFree SlotExclusive OwnedSlotNotWiped AnnounceVisibleWhileProtected"
  [CasAnnounceNoThreadIdWeakRelease]="NoUseAfterFree SlotExclusive OwnedSlotNotWiped AnnounceVisibleWhileProtected"
  [CasAnnounceResumeRefreshWeak]="NoUseAfterFree"
)

declare -A MODEL_NOTE=(
  [tso]="x86-TSO: the store buffer drains in FIFO order, only StoreLoad is relaxed."
  [arm]="Store-order relaxation of TSO: any pending store may become visible next, so a thread's stores can be observed out of program order."
  [armlb]="MODULE WeakMemory: each processor has its own view that catches up per field, in any order, so loads may be reordered against each other."
)

write_cfg() {
  local spec="$1" constants="$2" expected="$3" description="$4" out="$5" inv kv model
  {
    echo "\\* Generated by run.sh -- edit the table there, not this file."
    echo "\\* Expected: $expected. $description"
    for kv in $constants; do
      [[ "${kv%%=*}" == "Model" ]] && echo "\\* ${MODEL_NOTE[${kv#*=}]}"
    done
    echo "SPECIFICATION Spec"
    echo "CONSTANTS"
    for kv in $constants; do
      echo "    ${kv%%=*} = \"${kv#*=}\""
    done
    for inv in ${INVARIANTS[$spec]}; do
      echo "INVARIANT $inv"
    done
  } >"$out"
}

# note prints narration that only makes sense for a full run.
note() { [[ -n "$FILTER" ]] || echo "$@"; }

run() {
  local spec="$1" label="$2" constants="$3" expected_result="$4" description="$5"
  local name="${spec}_${label}" output status cfg

  [[ -z "$FILTER" || "$name" == *"$FILTER"* ]] || return 0
  matched=$((matched + 1))

  cfg="generated-${name}.cfg"
  write_cfg "$spec" "$constants" "$expected_result" "$description" "$FIXES/$cfg"

  output="$(mktemp)"
  echo ""
  echo "############################################################"
  echo "# $spec   (config: $cfg)"
  echo "# constants: $constants"
  echo "# expected: $expected_result ($description)"
  echo "############################################################"
  if (cd "$FIXES" && "${TLC[@]}" -config "$cfg" "$spec.tla") >"$output" 2>&1; then
    status=0
  else
    status=$?
  fi
  cat "$output"

  if [[ "$expected_result" == "HOLDS" ]]; then
    if [[ $status -eq 0 ]] && grep -q "Model checking completed. No error has been found." "$output"; then
      echo "# ---- PASS: HOLDS ----"
    else
      echo "# ---- FAIL: expected HOLDS; TLC exit code $status ----"
      failures=$((failures + 1))
    fi
  elif [[ $status -ne 0 ]] && grep -Eq "Error: Invariant .* is violated" "$output"; then
    echo "# ---- PASS: expected invariant violation observed ----"
  else
    echo "# ---- FAIL: expected invariant violation; TLC exit code $status ----"
    failures=$((failures + 1))
  fi

  rm -f "$output"
  [[ -n "${LE_KEEP_CFG:-}" ]] || rm -f "$FIXES/$cfg"
}

note "========= CAS-carries-epoch fix (the fix implemented in LightEpoch.cs) ========="
note "# The fix claims the slot WITH the announce -- CAS(localCurrentEpoch, 0 -> epoch)"
note "# -- instead of CASing threadId and then announcing with a plain store. The"
note "# locked-RMW count is unchanged; only the word being CASed differs."
note "#"
note "# Each spec is checked under BOTH store-buffer memory models (MODULE StoreBuffer):"
note "#   tso = x86-TSO, FIFO store-buffer drain, only StoreLoad relaxed"
note "#   arm = additionally relaxes StoreStore (any pending store may drain first)"
note "#"
note "# Each configuration is paired with a control that removes the fix, to prove"
note "# the spec is capable of detecting the bug it reports absent."

note ""
note "--- 1 reader + 1 reclaimer (Acquire, ProtectAndDrain, CS, Suspend) ---"
run CasAnnounceOneReader tso "Model=tso" HOLDS "CAS carries the announce (x86-TSO)"
run CasAnnounceOneReader arm "Model=arm" HOLDS "CAS carries the announce (+StoreStore)"

note ""
note "--- 2 readers contending for one slot + 1 reclaimer ---"
run CasAnnounceTwoReaders             tso "Model=tso" HOLDS    "slot reuse is safe (x86-TSO)"
run CasAnnounceTwoReaders             arm "Model=arm" HOLDS    "slot reuse is safe (+StoreStore)"
run CasAnnounceTwoReadersNoCas        tso "Model=tso" VIOLATED "control: no CAS on the epoch word (x86-TSO)"
run CasAnnounceTwoReadersNoCas        arm "Model=arm" VIOLATED "control: no CAS on the epoch word (+StoreStore)"
note "# Release() must unpublish the slot with a release store. These two rows are why."
run CasAnnounceTwoReadersPlainRelease tso "Model=tso" HOLDS    "control: plain Release survives TSO's FIFO drain"
run CasAnnounceTwoReadersPlainRelease arm "Model=arm" VIOLATED "control: plain Release lets the next owner's announce be wiped (+StoreStore)"
run CasAnnounceTwoReadersNoThreadId      tso "Model=tso" HOLDS    "threadId removed: epoch word alone owns the slot (x86-TSO)"
run CasAnnounceTwoReadersNoThreadId      arm "Model=arm" HOLDS    "threadId removed: epoch word alone owns the slot (+StoreStore)"
run CasAnnounceTwoReadersNoThreadIdNoCas tso "Model=tso" VIOLATED "control: no threadId AND no CAS -> both readers claim one slot (x86-TSO)"
run CasAnnounceTwoReadersNoThreadIdNoCas arm "Model=arm" VIOLATED "control: no threadId AND no CAS -> both readers claim one slot (+StoreStore)"

note ""
note "--- 2 symmetric peers: each protects AND reclaims, own slot each ---"
note "# The configuration Tsavorite actually runs: every session thread does"
note "# Resume / ProtectAndDrain / critical section / Suspend in a loop, and any"
note "# of them may also retire an object and run the scan -- while itself protected."
run CasAnnounceSymmetricPeers      tso "Model=tso" HOLDS    "self-reclaiming peers are safe (x86-TSO)"
run CasAnnounceSymmetricPeers      arm "Model=arm" HOLDS    "self-reclaiming peers are safe (+StoreStore)"
run CasAnnounceSymmetricPeersNoCas tso "Model=tso" VIOLATED "control: production ordering frees under a live peer (x86-TSO)"
run CasAnnounceSymmetricPeersNoCas arm "Model=arm" VIOLATED "control: production ordering frees under a live peer (+StoreStore)"

note ""
note "--- can Entry.threadId be deleted once the CAS owns the slot? ---"
note "# With the fix, CAS(localCurrentEpoch, 0 -> epoch) both claims and announces,"
note "# so threadId no longer participates in slot ownership and the scan never read"
note "# it. These specs delete the field and leave ownership to the claim CAS plus"
note "# the thread-private entry index (Metadata.Entries[instanceId]). LightEpoch.cs"
note "# keeps the field, because ThisInstanceProtected() still reports on it."
run CasAnnounceNoThreadId            tso "Model=tso" HOLDS    "slot reuse is safe with threadId deleted (x86-TSO)"
run CasAnnounceNoThreadId            arm "Model=arm" HOLDS    "slot reuse is safe with threadId deleted (+StoreStore)"
note "# Two controls on two different axes, so the HOLDS above cannot be an artifact"
note "# of deleting the field that the invariants were watching."
run CasAnnounceNoThreadIdNoCas       tso "Model=tso" VIOLATED "control: announce axis -- unfenced claim still detected (x86-TSO)"
run CasAnnounceNoThreadIdNoCas       arm "Model=arm" VIOLATED "control: announce axis -- unfenced claim still detected (+StoreStore)"
run CasAnnounceNoThreadIdStaleIndex  tso "Model=tso" VIOLATED "control: ownership axis -- a stale entry index now has nothing to disqualify it"
run CasAnnounceNoThreadIdStaleIndex  arm "Model=arm" VIOLATED "control: ownership axis -- a stale entry index now has nothing to disqualify it"
note "# Deleting threadId also deletes the only unfenced reader stores, so the two"
note "# runs above explore an identical state space and the 'arm' verdict is not"
note "# independent evidence. This pair weakens the unpublish to a release store"
note "# that may linger, which gives the store-order relaxation something to act on."
run CasAnnounceNoThreadIdWeakRelease tso "Model=tso" HOLDS    "release-only unpublish, threadId deleted (x86-TSO)"
run CasAnnounceNoThreadIdWeakRelease arm "Model=arm" HOLDS    "release-only unpublish may land late; late is conservative (+StoreStore)"

note ""
note "========= reader-side reordering (WeakMemory, per-processor views) ========="
note "# Everything above uses MODULE StoreBuffer, whose \"arm\" model relaxes STORE"
note "# visibility only. It is multi-copy atomic and has no load-load reordering, so"
note "# a load always returns the newest propagated value."
note "#"
note "# That is not strong enough. CasAnnounceSymmetricPeers HOLDS under \"arm\" while"
note "# the same algorithm faults on a Neoverse-N2 in seconds under the Resume+Refresh"
note "# sequence. MODULE WeakMemory adds the missing dimension: each processor has its"
note "# own view that catches up per FIELD, in any order, so a reader can observe the"
note "# bumped epoch while still holding a stale view of the unlink. This is what"
note "# motivates the Volatile.Read(ref CurrentEpoch) in ProtectAndDrain()."
run CasAnnounceResumeRefreshWeak plain_tso     "Model=tso   RefreshOrder=plain   AcquireOrder=cas" HOLDS    "plain refresh announce is safe under TSO"
run CasAnnounceResumeRefreshWeak plain_arm     "Model=arm   RefreshOrder=plain   AcquireOrder=cas" HOLDS    "store reordering alone does NOT expose it -- this is the false all-clear"
run CasAnnounceResumeRefreshWeak plain_armlb   "Model=armlb RefreshOrder=plain   AcquireOrder=cas" VIOLATED "reader announces E+1 on a stale view and frees the object it is reading"
run CasAnnounceResumeRefreshWeak release_armlb "Model=armlb RefreshOrder=release AcquireOrder=cas" VIOLATED "a release store publishes the announce but does not refresh the reader's view"
note "# The hazard is load-side message passing: the reclaimer already orders its unlink"
note "# before the epoch bump (Interlocked.Increment is a locked RMW), so the reader needs"
note "# only to observe that ordering. An acquire load of CurrentEpoch supplies it, and is"
note "# what x86 gives every load for free -- which is why the plain code is safe on x86."
run CasAnnounceResumeRefreshWeak acqload_armlb "Model=armlb RefreshOrder=acqload AcquireOrder=cas" HOLDS "an acquire load of CurrentEpoch is sufficient, and is free on x86"
note "# Two controls, so that the HOLDS above cannot be an artifact of the model."
note "# acqloadmp uses a STRICTLY WEAKER acquire that transfers only the two fields the"
note "# message-passing argument actually claims; it must still hold. acqloadself is a"
note "# near miss that refreshes only the field being loaded, transferring nothing, and"
note "# must still fail -- if it ever holds, the check has gone dead and neither HOLDS counts."
run CasAnnounceResumeRefreshWeak acqloadmp_armlb   "Model=armlb RefreshOrder=acqloadmp   AcquireOrder=cas" HOLDS    "the minimal message-passing guarantee alone is enough"
run CasAnnounceResumeRefreshWeak acqloadself_armlb "Model=armlb RefreshOrder=acqloadself AcquireOrder=cas" VIOLATED "a load that transfers nothing still fails, so the check is alive"
note "# Minimality of the OTHER half of the fix. The acquire announce and the refresh"
note "# announce fail in two DIFFERENT shapes and so need two different strengths."
note "# The refresh is message passing, which acquire/release closes. The acquire announce"
note "# is store buffering (the reclaimer must observe the reader's store), and SB is the"
note "# classic shape that release/acquire does NOT close -- it needs a full RMW."
note "# Both rows below keep the acquire-load fix on the refresh, so any violation they"
note "# report is attributable to the acquire announce alone."
run CasAnnounceResumeRefreshWeak acqplain_armlb   "Model=armlb RefreshOrder=acqload AcquireOrder=plain"   VIOLATED "the acquire-load fix alone is NOT enough: the announce still lingers"
run CasAnnounceResumeRefreshWeak acqrelease_armlb "Model=armlb RefreshOrder=acqload AcquireOrder=release" VIOLATED "a release store is not enough either, so the CAS is load-bearing"
run CasAnnounceResumeRefreshWeak fence_armlb      "Model=armlb RefreshOrder=fence   AcquireOrder=cas"     HOLDS    "a full StoreLoad barrier also closes it, but is strictly more than needed"

echo ""
if [[ -n "$FILTER" && $matched -eq 0 ]]; then
  echo "No spec matched filter '$FILTER'."
  exit 1
fi

if [[ $failures -ne 0 ]]; then
  echo "$failures spec result(s) did not match expectations."
  exit 1
fi

echo "All $matched spec result(s) matched expectations."
