#!/usr/bin/env bash
#
# Emit RyuJIT disassembly for the LightEpoch epoch operations, for x86-64 and
# AArch64, from a single x64 container.
#
# Usage (inside the image, with the repository mounted at /repo):
#   capture.sh [label=gitref ...]
# Default:
#   capture.sh fixed=HEAD main=origin/main
#
# Output: /out/<arch>-<label>.asm, matching the names already in ../jit/.
#
# LightEpoch is a standalone project, so each ref's epoch sources are lifted out
# whole rather than cherry-picked; refs from before that split fall back to the
# old in-Tsavorite.core layout.
#
# Method selection is by bare name, space separated; the Class:Method form
# silently matches nothing. The Op* wrappers in Program.cs are NoInlining so each
# epoch operation gets a standalone listing while its body still inlines the way
# it would at a real call site.

set -uo pipefail

REPO=${REPO:-/repo}
OUT=${OUT:-/out}

# LightEpoch lives in its own project, so the whole directory can be lifted out
# of a git ref and compiled as-is -- no guessing at what it depends on.
EPOCH_PROJECT_DIR=${EPOCH_PROJECT_DIR:-libs/storage/Tsavorite/cs/src/epoch}

# Refs from before the project split keep LightEpoch inside Tsavorite.core, where
# it reaches for Utility.Murmur3; UtilityShim.cs covers that so `main` can still
# be captured for comparison.
LEGACY_PATHS=${LEGACY_PATHS:-libs/storage/Tsavorite/cs/src/core/Epochs/LightEpoch.cs libs/storage/Tsavorite/cs/src/core/Epochs/IEpochAccessor.cs}

METHODS=${METHODS:-OpResume OpProtectAndDrain OpSuspend OpBumpCurrentEpoch BumpCurrentEpoch ComputeNewSafeToReclaimEpoch}

# rid:arch-label pairs. The arch label is what ../jit/ already uses.
RIDS=${RIDS:-linux-x64:x86 linux-arm64:arm64}

pairs=("$@")
if [ ${#pairs[@]} -eq 0 ]; then
    pairs=(fixed=HEAD main=origin/main)
fi

mkdir -p "$OUT"
failures=0

for pair in "${pairs[@]}"; do
    label=${pair%%=*}
    ref=${pair#*=}

    echo "=============================================================="
    echo "== $label  <-  $ref"
    echo "=============================================================="

    rm -rf /work/epoch
    mkdir -p /work/epoch
    source_desc=""

    if git -C "$REPO" cat-file -e "$ref:$EPOCH_PROJECT_DIR" 2>/dev/null; then
        git -C "$REPO" archive "$ref" "$EPOCH_PROJECT_DIR" \
            | tar -x -C /work --strip-components=5 --wildcards '*.cs'
        source_desc="$EPOCH_PROJECT_DIR (standalone project)"
    else
        missing=0
        for path in $LEGACY_PATHS; do
            if ! git -C "$REPO" cat-file -e "$ref:$path" 2>/dev/null; then
                missing=1
                break
            fi
            git -C "$REPO" show "$ref:$path" > "/work/epoch/$(basename "$path")"
        done
        if [ "$missing" -ne 0 ]; then
            echo "ERROR: $ref has neither $EPOCH_PROJECT_DIR nor the pre-split epoch sources." >&2
            failures=$((failures + 1))
            continue
        fi
        source_desc="$LEGACY_PATHS (pre-split layout)"
    fi

    for entry in $RIDS; do
        rid=${entry%%:*}
        arch=${entry##*:}
        asm="$OUT/$arch-$label.asm"
        raw=$(mktemp)

        echo "-- $rid -> $asm"
        rm -rf "/work/obj" "/work/bin"

        # Cross-targeting AArch64 needs the aarch64 objcopy; passing it for the
        # x64 target instead breaks the link.
        extra_args=()
        if [ "$rid" = "linux-arm64" ]; then
            extra_args+=(-p:ObjCopyName=aarch64-linux-gnu-objcopy)
        fi

        # The disassembly is written by RyuJIT during ILC codegen, which happens
        # before the native link. A cross-link failure therefore still leaves a
        # complete and valid listing, so the publish exit code is not the signal
        # to trust here -- the presence of the listing is.
        dotnet publish Disasm.csproj \
            -c Release \
            -r "$rid" \
            --self-contained \
            -p:PublishAot=true \
            -p:CaptureDisasm=true \
            -p:JitDisasmMethods="$METHODS" \
            "${extra_args[@]}" \
            > "$raw" 2>&1
        publish_status=$?

        if ! grep -q '; Assembly listing for method' "$raw"; then
            echo "ERROR: no disassembly captured for $rid/$label (publish exit $publish_status)." >&2
            echo "------- last 40 lines of the build log -------" >&2
            tail -n 40 "$raw" >&2
            failures=$((failures + 1))
            rm -f "$raw"
            continue
        fi

        {
            echo "; LightEpoch RyuJIT disassembly"
            echo ";   label      : $label"
            echo ";   git ref    : $ref ($(git -C "$REPO" rev-parse --short "$ref"))"
            echo ";   source     : $source_desc"
            echo ";   target     : $rid"
            echo ";   compiler   : NativeAOT ILC (hosts RyuJIT), $(dotnet --version) SDK"
            echo ";   methods    : $METHODS"
            echo ";"
            echo "; Generated by capture/capture.sh. Addresses and large immediates are"
            echo "; normalised by JitDisasmDiffable so these files diff cleanly."
            echo ";"
            # Keep only the listings; MSBuild progress lines are not evidence.
            sed -n '/; Assembly listing for method/,$p' "$raw"
        } > "$asm"

        count=$(grep -c '; Assembly listing for method' "$asm")
        echo "   captured $count method listing(s)"
        if [ "$publish_status" -ne 0 ]; then
            echo "   note: publish exited $publish_status (native link stage); codegen output is complete"
        fi
        rm -f "$raw"
    done

    rm -rf /work/epoch
done

echo
if [ "$failures" -ne 0 ]; then
    echo "$failures capture(s) failed."
    exit 1
fi
echo "All captures succeeded. Output in $OUT:"
ls -1 "$OUT"
