#!/usr/bin/env bash
#
# Emit RyuJIT disassembly for the LightEpoch epoch operations, for x86-64 and
# AArch64, from a single x64 container.
#
# Usage (inside the image, with the repository mounted at /repo):
#   capture.sh [gitref]
# Default:
#   capture.sh HEAD
#
# Output: /out/<arch>.asm -- one file per architecture, matching ../jit/.
#
# LightEpoch is a standalone project, so the epoch sources are lifted out whole
# rather than cherry-picked; whatever the ref builds is what gets compiled.
#
# Method selection is by bare name, space separated; the Class:Method form
# silently matches nothing. The Op* wrappers in Program.cs are NoInlining so each
# epoch operation gets a standalone listing while its body still inlines the way
# it would at a real call site.

set -uo pipefail

REPO=${REPO:-/repo}
OUT=${OUT:-/out}

# LightEpoch lives in its own project, so the whole directory can be lifted out
# of a git ref and compiled as-is -- no guessing at what it depends on.
EPOCH_PROJECT_DIR=${EPOCH_PROJECT_DIR:-libs/storage/Tsavorite/cs/src/epoch}

METHODS=${METHODS:-OpResume OpProtectAndDrain OpSuspend OpBumpCurrentEpoch BumpCurrentEpoch ComputeNewSafeToReclaimEpoch}

# rid:arch-label pairs. The arch label is what ../jit/ already uses.
RIDS=${RIDS:-linux-x64:x86 linux-arm64:arm64}

ref=${1:-HEAD}

mkdir -p "$OUT"
failures=0

echo "=============================================================="
echo "== $ref ($(git -C "$REPO" rev-parse --short "$ref"))"
echo "=============================================================="

if ! git -C "$REPO" cat-file -e "$ref:$EPOCH_PROJECT_DIR" 2>/dev/null; then
    echo "ERROR: $ref has no $EPOCH_PROJECT_DIR." >&2
    exit 1
fi

rm -rf /work/epoch
mkdir -p /work/epoch
git -C "$REPO" archive "$ref" "$EPOCH_PROJECT_DIR" \
    | tar -x -C /work --strip-components=5 --wildcards '*.cs'

for entry in $RIDS; do
    rid=${entry%%:*}
    arch=${entry##*:}
    asm="$OUT/$arch.asm"
    raw=$(mktemp)

    echo "-- $rid"
    rm -rf "/work/obj" "/work/bin"

    # Cross-targeting AArch64 needs the aarch64 objcopy; passing it for the
    # x64 target instead breaks the link.
    extra_args=()
    if [ "$rid" = "linux-arm64" ]; then
        extra_args+=(-p:ObjCopyName=aarch64-linux-gnu-objcopy)
    fi

    # The disassembly is written by RyuJIT during ILC codegen, which happens
    # before the native link. A cross-link failure therefore still leaves a
    # complete and valid listing, so the publish exit code is not the signal
    # to trust here -- the presence of the listing is.
    dotnet publish Disasm.csproj \
        -c Release \
        -r "$rid" \
        --self-contained \
        -p:PublishAot=true \
        -p:CaptureDisasm=true \
        -p:JitDisasmMethods="$METHODS" \
        "${extra_args[@]}" \
        > "$raw" 2>&1
    publish_status=$?

    if ! grep -q '; Assembly listing for method' "$raw"; then
        echo "ERROR: no disassembly captured for $rid (publish exit $publish_status)." >&2
        echo "------- last 40 lines of the build log -------" >&2
        tail -n 40 "$raw" >&2
        failures=$((failures + 1))
        rm -f "$raw"
        continue
    fi

    {
        echo "; ==========================================================================="
        echo "; LightEpoch RyuJIT disassembly -- $arch"
        echo ";"
        echo ";   git ref    : $ref ($(git -C "$REPO" rev-parse --short "$ref"))"
        echo ";   source     : $EPOCH_PROJECT_DIR"
        echo ";   target     : $rid"
        echo ";   compiler   : NativeAOT ILC (hosts RyuJIT), $(dotnet --version) SDK"
        echo ";   methods    : $METHODS"
        echo ";"
        echo "; Generated by capture/capture.sh. Addresses and large immediates are"
        echo "; normalised by JitDisasmDiffable so these files diff cleanly."
        echo "; ==========================================================================="
        echo
        # Keep only the listings; MSBuild progress lines are not evidence.
        sed -n '/; Assembly listing for method/,$p' "$raw"
    } > "$asm"

    count=$(grep -c '; Assembly listing for method' "$asm")
    echo "   captured $count method listing(s) -> $asm"
    if [ "$publish_status" -ne 0 ]; then
        echo "   note: publish exited $publish_status (native link stage); codegen output is complete"
    fi
    rm -f "$raw"
done

rm -rf /work/epoch

echo
if [ "$failures" -ne 0 ]; then
    echo "$failures capture(s) failed."
    exit 1
fi
echo "All captures succeeded. Output in $OUT:"
ls -1 "$OUT"
